# Generated by Django 3.2.8 on 2021-10-20 12:27

from django.db import migrations, models
import subject_book.utils


class Migration(migrations.Migration):

    dependencies = [
        ('subject_book', '0002_auto_20211020_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='original_name',
        ),
        migrations.AddField(
            model_name='uploads',
            name='media_url',
            field=models.FileField(default=1, upload_to=subject_book.utils.uploads_url_with_instance),
            preserve_default=False,
        ),
    ]
