# Generated by Django 3.2.8 on 2021-10-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_book', '0003_auto_20211020_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='new_name',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='path',
        ),
        migrations.AddField(
            model_name='uploads',
            name='original_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploads',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='content_type',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
