# Generated by Django 3.2.8 on 2021-10-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_book', '0004_auto_20211020_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='generated_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
